Bitcoin gold
BTCGPU/bitcoinjs-lib pull request #1
Opened 2018-03-27 18:27 UTC by Vutov

2018-04-02 19:43 UTC, h4x3rotab requested changes
Good job! Please take a look at some small problems.

2018-04-02 19:43 UTC, h4x3rotab commented on package.json
> +  "name": "bitcoinforksjs-lib",
Let's rename it as `bitcoingoldjs-lib`

2018-04-02 19:43 UTC, h4x3rotab commented on src/transaction.js
> +Transaction.SIGHASH_BITCOINCASHBIP143 = 0x40
Let's rename it to `Transaction.SIGHASH_FORKID `

2018-04-02 19:43 UTC, h4x3rotab commented on src/networks.js
> +    messagePrefix: '\x18Bitcoin Gold Signed Message:\n',
`\x18` is the hex of 24, which is the compact encoding of `len("Bitcoin Signed Message:\n")`.

As we are using "Bitcoin Gold Signed Message:\n", it should be `0x1d` (29 characters).

2018-04-02 19:43 UTC, h4x3rotab commented on src/networks.js
> +    messagePrefix: '\x18Bitcoin Gold Signed Message:\n',
ditto

2018-04-02 19:43 UTC, h4x3rotab commented on src/transaction.js
> +  // BIP143 sighash activated in BitcoinCash via 0x40 bit
s/BitcoinCash/Bitcoin Gold

2018-04-02 19:43 UTC, h4x3rotab commented on src/transaction.js
> +      throw new Error('Bitcoin Cash sighash requires value of input to be signed.')
s/Cash/Gold

2018-04-03 10:23 UTC, qasimsaleem1 commented
Are we working on some marketing of btg and when new exchange will add btg like bitflyer

2018-04-03 18:26 UTC, merged